### ISSUE TITLE
Can't fully automate Ubuntu 16.04 installs

### ISSUE THREAD

**Issue by ceejatec** [jrisch/ansible-xenserver-vm-deploy#1]
This probably isn't a bug with your stuff, but it seems as though you've been able to do this and I simply can't, so I thought I'd ask. I'm using Citrix XenServer 7.2.0 and trying to deploy an Ubuntu 16.04 guest. I use the "Ubuntu Xenial Xerus 16.04" template and I've got an ISO for 16.04.3 server which I insert into the virtual CD-ROM drive. But because this is a fully HVM template, there is no way to pass the kernel boot parameters - in other words, as far as I can tell the "xe vm-param-set PV-args" call has no effect. Without that there, it doesn't know to use my preseed file, and so the automation stops.

I've hunted here there and everywhere for a way around this, but this project here really seems to be the closest to achieving what I'd like. I feel confident this MUST be possible, so any pointers you might give from your own experience would be greatly appreciated!

**Comment by jrisch** [comment]
Hi @ceejatec I've run into the same problem, when using the standard templates in Xenserver 7.2 and later. It's not possible to pass boot args to a HVM based VM. My solution has been to install the VM with a PV template instead. I use these tasks to copy an old PV template to a new one:

```
# Install Ubuntu Xenial template if it does not exist
- name: Search for Ubuntu 16.04 amd64 template
  shell: xe template-list | grep "Ubuntu Xenial Xerus 16.04 (64-bit)"
  ignore_errors: True
  register: ubuntu_xenial_amd64
  tags: [xenserver,templates]

- name: Find UUID of older template
  shell: xe template-list name-label="Ubuntu Trusty Tahr 14.04 (64-bit)" params=uuid --minimal
  register: old_template_uuid_ubuntu_xenial_amd64
  when: ubuntu_xenial_amd64.rc == 1
  tags: [xenserver,templates]

- name: Create new template
  shell: xe vm-clone uuid={{ old_template_uuid_ubuntu_xenial_amd64.stdout }} new-name-label="Ubuntu Xenial Xerus 16.04 (64-bit)"
  register: new_template_uuid_ubuntu_xenial_amd64
  when: ubuntu_xenial_amd64.rc == 1
  tags: [xenserver,templates]

- name: Register new template
  shell: xe template-param-set other-config:default_template=true other-config:debian-release=xenial uuid={{ new_template_uuid_ubuntu_xenial_amd64.stdout }}
  when: ubuntu_xenial_amd64.rc == 1
  tags: [xenserver,templates]

# Make sure that the Ubuntu Xenial Xerus template has the correct PV-args
- name: Find Ubuntu Xenial Xerus 16.04 (64-bit) template uuid
  shell: xe template-list | grep "Ubuntu Xenial Xerus 16.04 (64-bit)" -B1 | grep uuid | cut -d ":" -f2 | cut -c 2-
  register: xenial_uuid
  tags: [xenserver,templates]

- name: Set correct PV-args for Ubuntu Xenial Xerus 16.04 (64-bit) template
  shell: xe template-param-set PV-args="--- quiet console=hvc0" uuid={{ xenial_uuid.stdout }}
  tags: [xenserver,templates]
```

You could add "PV" to the name of the new template, to avoid confusion.

When the installation has finished, it should be possible to convert the VM to a PVHVM based VM. But I can't find the related material on that right now.

Another alternative would be to use a BOOTP server, that passes the preseed params to the VM as part of the boot process. Or, if you use Xen Orchestra instead of XenCenter, you could make a CloudInit based template, that is HVM based. This makes preseed installations obsolete (and this whole GitHub repo obsolete), as the CloudInit template is image based. 

Hope this helps.

**Comment by ceejatec** [comment]
Thanks for the detailed response! I appreciate the time, and I will explore that setup.

I've managed to make headway by going a slightly different approach - I created a customized .iso with a kickstart file burned into it, so all it does on boot is install the OS the way I want and reboot. Not super-flexible, but relatively easy to automate. I did have to also burn in the XenServer 7.4 xe-guest-utilities .deb package and install that automatically, but at that point the VM's IP address was accessible through 'xe vm-param-get uuid={{ vmuuid.stdout }} param-name=networks param-key=0/ip' and I could start automating additional software setup.

FYI, I'm using Ubuntu 18.04 now that it's released. If you just go to the Download page on ubuntu.com for Ubuntu Server 18.04, you'll get a new image called ubuntu-18.04-live-server-amd64.iso, which uses a completely new installer that doesn't appear to work with either preseed or kickstart files. (I'm sure there will be a different way to automate it in future - it asks very few questions as it is.) However you can go to the "Alternative Ubuntu Server installer" page and get a classic ubuntu-18.04-server-amd64.iso which operates the same as Ubuntu 16 and earlier with preseed and kickstart files. Something to watch out for if you upgrade later.

Thanks again! I'm going to close this issue out now since there doesn't seem to be anything wrong with this package itself.
